# Generated by Django 6.0.8 on 2026-08-16 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(help_text='HTML — static lesson content, DB-stored, no CMS.')),
                ('quiz_questions', models.JSONField(help_text='{"questions": [{"question": str, "options": [str], "correct": int}]}')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.PositiveIntegerField()),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
